jar {
  manifest {
    attributes('Automatic-Module-Name': 'mOkhttp3.dnsoverhttps')
  }
}

dependencies {
  api project(':mOkhttp')
  compileOnly deps.jsr305

  testImplementation project(':mOkhttp-testing-support')
  testImplementation project(':mockwebserver')
  testImplementation deps.conscrypt
  testImplementation deps.junit
  testImplementation deps.assertj
}

afterEvaluate { project ->
  project.tasks.dokka {
    outputDirectory = "$rootDir/docs/4.x"
    outputFormat = 'gfm'
  }
}
