dependencies {
  testImplementation files("../libs/okio-jvm-2.8.0.jar")
  testImplementation deps.moshi
  testImplementation project(':mOkhttp')
  testImplementation project(':mOkhttp-testing-support')
  testImplementation project(':mockwebserver')
  testImplementation deps.junit
  testImplementation deps.assertj
}
